server:
  port: 9999
  servlet:
    context-path: /gms
spring:
  application:
    name: gms
  profiles:
    active: dev
  datasource:
    username: root
    password: d2p9bupt
    url: jdbc:mysql://localhost:3306/gms
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /html/
      suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/
